project:
  type: website

website:
  title: ""
  sidebar:
    contents:
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



