---
title: "My Top Anime Song"
format:
  dashboard:
    logo: "images/logo.png"
    orientation: columns
---

```{r, load packages}
#| echo: false
#| include: false
library(tidyverse)
library(gt)
library(googlesheets4)
library(quarto)
```

```{r, import data}
gs4_deauth()

df = read_sheet("https://docs.google.com/spreadsheets/d/1uNYfeghUGPkpMYVwhLSkxx81_x8Syr7t9W8D4Ry4hag/edit?gid=0#gid=0")

```

## Column {width="60%"}

### Row {height="10%"}
Placeholder text for column 

### Row {height="90%"}

```{r}
#| expandable: false

df |> 
  select(-link) |> 
  gt() |> 
   tab_options(
    table.width = pct(100),
    table.border.top.color = "white",
    table.border.bottom.color = "white",
    column_labels.font.weight = "bold",
    column_labels.background.color = "#f4f4f4",
    row.striping.background_color = "#f9f9f9"
  ) %>%

  # Column styling
  cols_align(align = "center", columns = everything()) %>%
  cols_width(
    Title ~ px(200),
    Artist ~ px(250),
    Anime ~ px(250)
  ) %>%
  
  # Font Styling
  opt_table_font(
    font = google_font("Poppins"),
    weight = 400
  ) %>%
  
  # Add subtle row striping
  opt_row_striping() %>%
  
  # Color table borders softly
  tab_style(
    style = list(
      cell_borders(sides = "all", color = "lightgrey", weight = px(0.5))
    ),
    locations = cells_body()
  )
```

## Column {width="40%"}

### Row {height="10%"}

```{r, sendtoojs}
#| echo: false
#| include: false

ojs_define(ojs_df = df)
```

```{ojs}
//| expandable: false

df_transpose = transpose(ojs_df)

viewof songDropdown = Inputs.select(
  df_transpose.map(d => d.Title),
  {
  label: "Chooose a song",
  unique: true,
  
}
)

```

### Row {height = "80%"}

```{ojs}
//| expandable: false

html`
    ${songDropdown ? html`
      <iframe width="100%" height="500" src="${df_transpose.find(d => d.Title === songDropdown).link}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    ` : "Please select a song from the dropdown"}
`
```

### Row {height = "10%"}

::: {.card}

:::


